deck = {"AH":{"value": 11,
             "show": "yes",
             "symbol": "♡",
             "face": "A",  
            },
        "2H":{ "value": 2,
              "show": "yes",
              "symbol": "♡",
              "face": "2",  
                    },
        "3H":{ "value": 3,
              "show": "yes",
              "symbol": "♡",
              "face": "3",  
                    },
        "4H":{ "value": 4,
              "show": "yes",
              "symbol": "♡",
              "face": "4",  
                    },
        "5H":{ "value": 5,
              "show": "yes",
              "symbol": "♡",
              "face": "5",  
                    },
        "6H":{ "value": 6,
              "show": "yes",
              "symbol": "♡",
              "face": "6",  
                    },
        "7H":{ "value": 7,
              "show": "yes",
              "symbol": "♡",
              "face": "7",  
                    },
        "8H":{ "value": 8,
              "show": "yes",
              "symbol": "♡",
              "face": "8",  
                    },
        "9H":{ "value": 9,
              "show": "yes",
              "symbol": "♡",
              "face": "9",  
                    },
        "10H":{ "value": 10,
              "show": "yes",
              "symbol": "♡",
              "face": "10",  
                    },
        "JH":{ "value": 10,
              "show": "yes",
              "symbol": "♡",
              "face": "J",  
                    },
        "QH":{ "value": 10,
              "show": "yes",
              "symbol": "♡",
              "face": "Q",  
                    },
        "KH":{ "value": 10,
              "show": "yes",
              "symbol": "♡",
              "face": "K",  
                    },
        "AD":{"value": 11,
             "show": "yes",
             "symbol": "♢",
             "face": "A",  
            },
        "2D":{ "value": 2,
              "show": "yes",
              "symbol": "♢",
              "face": "2",  
                    },
        "3D":{ "value": 3,
              "show": "yes",
              "symbol": "♢",
              "face": "3",  
                    },
        "4D":{ "value": 4,
              "show": "yes",
              "symbol": "♢",
              "face": "4",  
                    },
        "5D":{ "value": 5,
              "show": "yes",
              "symbol": "♢",
              "face": "5",  
                    },
        "6D":{ "value": 6,
              "show": "yes",
              "symbol": "♢",
              "face": "6",  
                    },
        "7D":{ "value": 7,
              "show": "yes",
              "symbol": "♢",
              "face": "7",  
                    },
        "8D":{ "value": 8,
              "show": "yes",
              "symbol": "♢",
              "face": "8",  
                    },
        "9D":{ "value": 9,
              "show": "yes",
              "symbol": "♢",
              "face": "9",  
                    },
        "10D":{ "value": 10,
              "show": "yes",
              "symbol": "♢",
              "face": "10",  
                    },
        "JD":{ "value": 10,
              "show": "yes",
              "symbol": "♢",
              "face": "J",  
                    },
        "QD":{ "value": 10,
              "show": "yes",
              "symbol": "♢",
              "face": "Q",  
                    },
        "KD":{ "value": 10,
              "show": "yes",
              "symbol": "♢",
              "face": "K",  
                    },
        "AC":{"value": 11,
             "show": "yes",
             "symbol": "♧",
             "face": "A",  
            },
        "2C":{ "value": 2,
              "show": "yes",
              "symbol": "♧",
              "face": "2",  
                    },
        "3C":{ "value": 3,
              "show": "yes",
              "symbol": "♧",
              "face": "3",  
                    },
        "4C":{ "value": 4,
              "show": "yes",
              "symbol": "♧",
              "face": "4",  
                    },
        "5C":{ "value": 5,
              "show": "yes",
              "symbol": "♧",
              "face": "5",  
                    },
        "6C":{ "value": 6,
              "show": "yes",
              "symbol": "♧",
              "face": "6",  
                    },
        "7C":{ "value": 7,
              "show": "yes",
              "symbol": "♧",
              "face": "7",  
                    },
        "8C":{ "value": 8,
              "show": "yes",
              "symbol": "♧",
              "face": "8",  
                    },
        "9C":{ "value": 9,
              "show": "yes",
              "symbol": "♧",
              "face": "9",  
                    },
        "10C":{ "value": 10,
              "show": "yes",
              "symbol": "♧",
              "face": "10",  
                    },
        "JC":{ "value": 10,
              "show": "yes",
              "symbol": "♧",
              "face": "J",  
                    },
        "QC":{ "value": 10,
              "show": "yes",
              "symbol": "♧",
              "face": "Q",  
                    },
        "KC":{ "value": 10,
              "show": "yes",
              "symbol": "♧",
              "face": "K",  
                    },
        "AS":{"value": 11,
             "show": "yes",
             "symbol": "♤",
             "face": "A",  
            },
        "2S":{ "value": 2,
              "show": "yes",
              "symbol": "♤",
              "face": "2",  
                    },
        "3S":{ "value": 3,
              "show": "yes",
              "symbol": "♤",
              "face": "3",  
                    },
        "4S":{ "value": 4,
              "show": "yes",
              "symbol": "♤",
              "face": "4",  
                    },
        "5S":{ "value": 5,
              "show": "yes",
              "symbol": "♤",
              "face": "5",  
                    },
        "6S":{ "value": 6,
              "show": "yes",
              "symbol": "♤",
              "face": "6",  
                    },
        "7S":{ "value": 7,
              "show": "yes",
              "symbol": "♤",
              "face": "7",  
                    },
        "8S":{ "value": 8,
              "show": "yes",
              "symbol": "♤",
              "face": "8",  
                    },
        "9S":{ "value": 9,
              "show": "yes",
              "symbol": "♤",
              "face": "9",  
                    },
        "10S":{ "value": 10,
              "show": "yes",
              "symbol": "♤",
              "face": "10",  
                    },
        "JS":{ "value": 10,
              "show": "yes",
              "symbol": "♤",
              "face": "J",  
                    },
        "QS":{ "value": 10,
              "show": "yes",
              "symbol": "♤",
              "face": "Q",  
                    },
        "KS":{ "value": 10,
              "show": "yes",
              "symbol": "♤",
              "face": "K",  
                    },
}


